### PR TITLE
Update xdxf_strict.dtd

### PR DESCRIPTION
**Pull request by zero00072**
More follow DTD rules.
It still have a DTD syntax error at the "def" element.

### CODE REVIEW

**Comment by soshial** [comment]
Thank you so much for working on this DTD document! May I ask what you use to test the compliance with the syntax?

Also, are strings' movements (that you made in the beginning of `xdxf_strict.dtd
`) simply representational or they are prescribed by the standard?

**Comment by zero00072** [comment]
Hello! Thanks to review. I found it because of that Goldendict references to this DTD standard.

I fixed it just for I want declare what the DTD's logic. I found something I can't understand, so I just push it to http://www.validome.org/grammar/ to validated it. And then I known what you defined and fixed some little loop problems.

It is not follow any standard but mirror the http://www.w3.org/2001/XMLSchema.dtd style to stylish your DTD. You can just cancel my changes about style and comments.

But the "def" tag have a loop so that I can't fix it. This may need to reconstruct your DTD logic.

**Comment by soshial** [comment]
It would be nice if you could leave only those changes that are important. Without stylishing, that is :) Thank you.

**Comment by zero00072** [comment]
OK, give me hours. I will fixed it by only important thing based on your new push.

**Comment by zero00072** [comment]
OK, I have fixed it without stylish.

**Comment by soshial** [comment]
Thank you very much! I fixed everything and made a lot of changes.

**Pull request closed without merging**
